# Project Euler problem #2
# http://projecteuler.net/index.php?section=problems&id=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonaccis, target, a, b = [], 4000000, 0, 2
until b > target
  fibonaccis << b
  a, b = b, b * 4 + a
end
print fibonaccis.inject(:+)
